### PR TITLE
Add spike report into case service dupe identifiers on case groups

### PR DESCRIPTION
**Pull request by NickGrantX**
Spike report for Trello card: https://trello.com/c/HOf8732Z/415-spike-work-out-where-partyid-and-case-is-used-2-days

### CODE REVIEW

**Review by ChristopherMShelton — DISMISSED** [review]

**Comment by shahi645** [comment]
@NickGrantONS What is your recommendation, which should we get rid of, `business_party_id` or `sample_unit_ref` (ru_ref)?

**Comment by NickGrantX** [comment]
@shahi645 I would get rid of `partyid`, especially as it's not used by social

**Review by shahi645 — DISMISSED** [review]
Happy with this, could add your recommendations here to but not super important

**Comment by NickGrantX** [comment]
Actually I'm maybe changing my mind because removing partyId will break the interface contract, requiring Action, Party and Response Operations UI to be changed.

I think it's more work to get rid of partyID, but it's probably the right thing to do though.

**Review by gavinleeedwards — DISMISSED** [review]
Looks good.  Could add the recommendation to the report that you put in the PR comment, with next steps (don't know how far this spike needs to go) but you've answered the question on the Trello card so happy to approve.

**Comment by NickGrantX** [comment]
Added recommendations to spike report per comments from @shahi645 and @gavinleeedwards

**Review by mfcrocker — APPROVED** [review]
Especially with the state of our work at the moment, I think we're in a position to do this the hard, clean way :)

**Pull request merged**
